import { FindPokemonImage } from './../assets/img/pokemons'

export default [{
        "id": "#001",
        "photo": FindPokemonImage('bulbasaur'),
        "name": "Bulbasaur",
        "alias": "",
        "types": [],
        "egg_groups": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#002",
        "photo": FindPokemonImage('ivysaur'),
        "name": "Ivysaur",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#003",
        "photo": FindPokemonImage('venosaur'),
        "name": "Venosaur",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#004",
        "photo": FindPokemonImage('charmander'),
        "name": "Charmander",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#005",
        "photo": FindPokemonImage('charmeleon'),
        "name": "Charmeleon",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#006",
        "photo": FindPokemonImage('charizard'),
        "name": "Charizard",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#007",
        "photo": FindPokemonImage('squirtle'),
        "name": "Squirtle",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#008",
        "photo": FindPokemonImage('wartortle'),
        "name": "Wartortle",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#009",
        "photo": FindPokemonImage('blastoise'),
        "name": "Blastoise",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#010",
        "photo": FindPokemonImage('caterpie'),
        "name": "Caterpie",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#011",
        "photo": FindPokemonImage('metapod'),
        "name": "Metapod",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#012",
        "photo": FindPokemonImage('butterfree'),
        "name": "Butterfree",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#013",
        "photo": FindPokemonImage('weedle'),
        "name": "Weedle",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#014",
        "photo": FindPokemonImage('kakuna'),
        "name": "Kakuna",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#015",
        "photo": FindPokemonImage('beedrill'),
        "name": "Beedrill",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#016",
        "photo": FindPokemonImage('pidgey'),
        "name": "Pidgey",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#017",
        "photo": FindPokemonImage('pidgeotto'),
        "name": "Pidgeotto",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#018",
        "photo": FindPokemonImage('pidgeot'),
        "name": "Pidgeot",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#019",
        "photo": FindPokemonImage('rattata'),
        "name": "Rattata",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#020 ",
        "photo": FindPokemonImage('raticate'),
        "name": "Raticate",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#021",
        "photo": FindPokemonImage('spearow'),
        "name": "Spearow",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#022",
        "photo": FindPokemonImage('fearow'),
        "name": "Fearow",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#023",
        "photo": FindPokemonImage('ekans'),
        "name": "Ekans",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#024",
        "photo": FindPokemonImage('arbok'),
        "name": "Arbok",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#025",
        "photo": FindPokemonImage('pikachu'),
        "name": "Pikachu",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#026",
        "photo": FindPokemonImage('raichu'),
        "name": "Raichu",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#027",
        "photo": FindPokemonImage('sandshrew'),
        "name": "Sandshrew",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#028",
        "photo": FindPokemonImage('sandslash'),
        "name": "Sandslash",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#029",
        "photo": FindPokemonImage('nidoran_f'),
        "name": "Nidoran ♀",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#030",
        "photo": FindPokemonImage('nidorina'),
        "name": "Nidorina",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#031",
        "photo": FindPokemonImage('nidoqueen'),
        "name": "Nidoqueen",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#032",
        "photo": FindPokemonImage('nidoran_m'),
        "name": "Nidoran ♂",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#033",
        "photo": FindPokemonImage('nidorino'),
        "name": "Nidorino",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#034",
        "photo": FindPokemonImage('nidoking'),
        "name": "Nidoking",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#035",
        "photo": FindPokemonImage('clefairy'),
        "name": "Clefairy",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#036",
        "photo": FindPokemonImage('clefable'),
        "name": "Clefable",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#037",
        "photo": FindPokemonImage('vulpix'),
        "name": "Vulpix",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#038",
        "photo": FindPokemonImage('ninetales'),
        "name": "Ninetales",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#039",
        "photo": FindPokemonImage('jigglypuff'),
        "name": "Jigglypuff",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#040",
        "photo": FindPokemonImage('wigglytuff'),
        "name": "Wigglytuff",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#041",
        "photo": FindPokemonImage('zubat'),
        "name": "Zubat",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#042",
        "photo": FindPokemonImage('golbat'),
        "name": "Golbat",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#043",
        "photo": FindPokemonImage('oddish'),
        "name": "Oddish",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#044",
        "photo": FindPokemonImage('gloom'),
        "name": "Gloom",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#045",
        "photo": FindPokemonImage('vileplume'),
        "name": "Vileplume",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#046",
        "photo": FindPokemonImage('paras'),
        "name": "Paras",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#047",
        "photo": FindPokemonImage('parasect'),
        "name": "Parasect",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#048",
        "photo": FindPokemonImage('venonat'),
        "name": "Venonat",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#049",
        "photo": FindPokemonImage('venomoth'),
        "name": "Venomoth",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#050",
        "photo": FindPokemonImage('diglett'),
        "name": "Diglett",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#051",
        "photo": FindPokemonImage('dugtrio'),
        "name": "Dugtrio",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#052",
        "photo": FindPokemonImage('meowth'),
        "name": "Meowth",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#053",
        "photo": FindPokemonImage('persian'),
        "name": "Persian",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#054",
        "photo": FindPokemonImage('psyduck'),
        "name": "Psyduck",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#055",
        "photo": FindPokemonImage('golduck'),
        "name": "Golduck",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#056",
        "photo": FindPokemonImage('mankey'),
        "name": "Mankey",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#057",
        "photo": FindPokemonImage('primeape'),
        "name": "Primeape",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#058",
        "photo": FindPokemonImage('growlithe'),
        "name": "Growlithe",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#059",
        "photo": FindPokemonImage('arcanine'),
        "name": "Arcanine",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#060",
        "photo": FindPokemonImage('poliwag'),
        "name": "Poliwag",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#061",
        "photo": FindPokemonImage('poliwhirl'),
        "name": "Poliwhirl",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#062",
        "photo": FindPokemonImage('poliwrath'),
        "name": "Poliwrath",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#063",
        "photo": FindPokemonImage('abra'),
        "name": "Abra",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#064",
        "photo": FindPokemonImage('kadabra'),
        "name": "Kadabra",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#065",
        "photo": FindPokemonImage('alakazam'),
        "name": "Alakazam",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#066",
        "photo": FindPokemonImage('machop'),
        "name": "Machop",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#067",
        "photo": FindPokemonImage('machoke'),
        "name": "Machoke",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#068",
        "photo": FindPokemonImage('machamp'),
        "name": "Machamp",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#069",
        "photo": FindPokemonImage('bellsprout'),
        "name": "Bellsprout",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#070",
        "photo": FindPokemonImage('weepinbell'),
        "name": "Weepinbell",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#071",
        "photo": FindPokemonImage('victreebell'),
        "name": "Victreebell",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#072",
        "photo": FindPokemonImage('tentacool'),
        "name": "Tentacool",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#073",
        "photo": FindPokemonImage('tentacruel'),
        "name": "Tentacruel",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#074",
        "photo": FindPokemonImage('geodude'),
        "name": "Geodude",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#075",
        "photo": FindPokemonImage('graveler'),
        "name": "Graveler",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#076",
        "photo": FindPokemonImage('golem'),
        "name": "Golem",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#077",
        "photo": FindPokemonImage('ponyta'),
        "name": "Ponyta",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#078",
        "photo": FindPokemonImage('rapidash'),
        "name": "Rapidash",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#079",
        "photo": FindPokemonImage('slowpoke'),
        "name": "Slowpoke",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#080",
        "photo": FindPokemonImage('slowbro'),
        "name": "Slowbro",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#081",
        "photo": FindPokemonImage('magnemite'),
        "name": "Magnemite",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#082",
        "photo": FindPokemonImage('magneton'),
        "name": "Magneton",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#083",
        "photo": FindPokemonImage('farfetch_d'),
        "name": "Farfetch'd",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#084",
        "photo": FindPokemonImage('doduo'),
        "name": "Doduo",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#085",
        "photo": FindPokemonImage('dodrio'),
        "name": "Dodrio",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#086",
        "photo": FindPokemonImage('seel'),
        "name": "Seel",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#087",
        "photo": FindPokemonImage('dewgong'),
        "name": "Dewgong",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#088",
        "photo": FindPokemonImage('grimer'),
        "name": "Grimer",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#089",
        "photo": FindPokemonImage('muk'),
        "name": "Muk",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#090",
        "photo": FindPokemonImage('shellder'),
        "name": "Shellder",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#091",
        "photo": FindPokemonImage('cloyster'),
        "name": "Cloyster",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#092",
        "photo": FindPokemonImage('gastly'),
        "name": "Gastly",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#093",
        "photo": FindPokemonImage('haunter'),
        "name": "Haunter",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#094",
        "photo": FindPokemonImage('gengar'),
        "name": "Gengar",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#095",
        "photo": FindPokemonImage('onix'),
        "name": "Onix",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#096",
        "photo": FindPokemonImage('drowzee'),
        "name": "Drowzee",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#097",
        "photo": FindPokemonImage('hypno'),
        "name": "Hypno",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#098",
        "photo": FindPokemonImage('krabby'),
        "name": "Krabby",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#099",
        "photo": FindPokemonImage('kingler'),
        "name": "Kingler",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#100",
        "photo": FindPokemonImage('voltorb'),
        "name": "Voltorb",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#101",
        "photo": FindPokemonImage('electrode'),
        "name": "Electrode",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#102",
        "photo": FindPokemonImage('exeggcute'),
        "name": "exeggcute",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#103",
        "photo": FindPokemonImage('exeggutor'),
        "name": "Exeggutor",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#104",
        "photo": FindPokemonImage('cubone'),
        "name": "Cubone",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#105",
        "photo": FindPokemonImage('marowak'),
        "name": "Marowak",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#106",
        "photo": FindPokemonImage('hitmonlee'),
        "name": "Hitmonlee",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#107",
        "photo": FindPokemonImage('hitmonchan'),
        "name": "Hitmonchan",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#108",
        "photo": FindPokemonImage('licktung'),
        "name": "Licktung",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#109",
        "photo": FindPokemonImage('koffing'),
        "name": "Koffing",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#110",
        "photo": FindPokemonImage('weezing'),
        "name": "Weezing",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#111",
        "photo": FindPokemonImage('rhyhorn'),
        "name": "Rhyhorn",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#112",
        "photo": FindPokemonImage('rhydon'),
        "name": "Rhydon",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#113",
        "photo": FindPokemonImage('chansey'),
        "name": "Chansey",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#114",
        "photo": FindPokemonImage('tangela'),
        "name": "Tangela",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#115",
        "photo": FindPokemonImage('kangaskhan'),
        "name": "Kangaskhan",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#116",
        "photo": FindPokemonImage('horsea'),
        "name": "Horsea",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#117",
        "photo": FindPokemonImage('seadra'),
        "name": "Seadra",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#118",
        "photo": FindPokemonImage('goldeen'),
        "name": "Goldeen",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#119",
        "photo": FindPokemonImage('seaking'),
        "name": "Seaking",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#120",
        "photo": FindPokemonImage('staryu'),
        "name": "Staryu",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#121",
        "photo": FindPokemonImage('starmie'),
        "name": "Starmie",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#122",
        "photo": FindPokemonImage('mr_mime'),
        "name": "Mr. Mime",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#123",
        "photo": FindPokemonImage('scyther'),
        "name": "Scyther",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#124",
        "photo": FindPokemonImage('jynx'),
        "name": "Jynx",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#125",
        "photo": FindPokemonImage('electabuzz'),
        "name": "Electabuzz",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#126",
        "photo": FindPokemonImage('magmar'),
        "name": "Magmar",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#127",
        "photo": FindPokemonImage('pinsir'),
        "name": "Pinsir",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#128",
        "photo": FindPokemonImage('tauros'),
        "name": "Tauros",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#129",
        "photo": FindPokemonImage('magikarp'),
        "name": "Magikarp",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#130",
        "photo": FindPokemonImage('gyarados'),
        "name": "Gyarados",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#131",
        "photo": FindPokemonImage('lapras'),
        "name": "Lapras",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#132",
        "photo": FindPokemonImage('ditto'),
        "name": "Ditto",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#133",
        "photo": FindPokemonImage('eevee'),
        "name": "Eevee",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#134",
        "photo": FindPokemonImage('vaporeon'),
        "name": "Vaporeon",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#135",
        "photo": FindPokemonImage('jolteon'),
        "name": "Jolteon",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#136",
        "photo": FindPokemonImage('flareon'),
        "name": "Flareon",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#137",
        "photo": FindPokemonImage('porygon'),
        "name": "Porygon",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#138",
        "photo": FindPokemonImage('omanyte'),
        "name": "Omanyte",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#139",
        "photo": FindPokemonImage('omastar'),
        "name": "Omastar",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#140",
        "photo": FindPokemonImage('kabuto'),
        "name": "Kabuto",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#141",
        "photo": FindPokemonImage('kabutops'),
        "name": "Kabutops",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#142",
        "photo": FindPokemonImage('aerodactyl'),
        "name": "Aerodactyl",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#143",
        "photo": FindPokemonImage('snorlax'),
        "name": "Snorlax",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#144",
        "photo": FindPokemonImage('articuno'),
        "name": "Articuno",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#145",
        "photo": FindPokemonImage('zapdos'),
        "name": "Zapdos",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#146",
        "photo": FindPokemonImage('moltres'),
        "name": "Moltres",
        "alias": "",
        "type": [],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#147",
        "photo": FindPokemonImage('dratini'),
        "name": "Dratini",
        "alias": "",
        "type": [11],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#148",
        "photo": FindPokemonImage('dragonair'),
        "name": "Dragonair",
        "alias": "",
        "type": [11],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#149",
        "photo": FindPokemonImage('dragonite'),
        "name": "Dragonite",
        "alias": "",
        "type": [11, 4],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#150",
        "photo": FindPokemonImage('mewtwo'),
        "name": "Mewtwo ",
        "alias": "",
        "type": [7],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    },
    {
        "id": "#151",
        "photo": FindPokemonImage('mew'),
        "name": "Mew",
        "alias": "",
        "type": [7],
        "egg_group": [],
        "category_id": "",
        "moves": [],
        "region_id": 1,
        "generation_id": 1
    }
]